//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemImage
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ItemId { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
