//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int Id { get; set; }
        public int ProducerId { get; set; }
        public int ItemId { get; set; }
        public int Capacity { get; set; }
        public int Weight { get; set; }
        public float Display { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
